language: rust
sudo: false
cache: cargo

stages:
- name: test
- name: deploy
  if: tag IS present

rust:
- nightly-2018-11-03
- nightly
- beta
- stable
- 1.20.0

script:
- cargo test --all
- cargo test --all --release

matrix:
  allow_failures:
  - rust: nightly
  include:
  - name: cargo test
    rust: stable
    os: osx

  - name: cargo test
    rust: stable
    os: windows

  - name: cargo test -Z minimal-versions
    script:
    - cargo update -Z minimal-versions
    - cargo test --all

  - name: cargo fmt
    install:
    - rustup component add rustfmt-preview
    script:
    - cargo fmt --all -- --check

  - name: cargo clippy
    install:
    - rustup component add clippy-preview
    script:
    - cargo clippy --all --all-targets -- -D warnings

  - stage: deploy
    rust: stable
    script:
    - grep 'version = "'"$TRAVIS_TAG"'"' Cargo.toml || echo 'Tag does not match version in Cargo.toml'
    - gpg --keyserver pool.sks-keyservers.net --recv-keys $(tail -n +2 .authorized_keys)
    - git tag --verify "$TRAVIS_TAG"
    deploy:
      provider: cargo
      token:
        secure: aTakje4LmBBQhRX5RVxUbrZhthzDIYpPUg1agayXVp+j3LXRMwlh8au6qLEupYCglp2wHZ3FLd0bW3fIaSPjOjC/aySdMdgszJR71ytajYW7F50Gkeoc+e3dr7vI+8Ay3lG/I+9kPPdc38WjguvqWzMwqp6CDCfYDfzf4msAy4lvsg7gf2SWmcr8Cush0CGsp1no4hANRCiWuwbg2kVF2ii8ZUYDXQh1Td6kqOQxLqBvNH6TuQFeAnkUZ1gFgR3EDID1Tys7IRaB49z6D+6o3nR+LeJUVuF+DVav9MPDlrYlvUX42uVpXc/+1K9sUUmuPKFT6N/MuZf0huQ7ryH23wvwFUkeYV0mPeNDjMzZmFPL2ns27fJkt+KkF1uEcuMWiNHcbant5a8bb7Ylj19JG0Gr3M9zl/Z02sMzNNvLCmvZklgGdvTOhqaLyCxyaqcDzBO1FOf/lgrqymsFAUmT6UWxnW3vWWqydjxxv+tlppG10wWjmQuOBfKjehl2qt0l38zh0ZEN6AUkQgD5Wds6DpQhzkyn9Bx7cS6UEnbIp64XxvRFCvgBRvlp1ZIhFSScS7vbHJ1VolfcA3d2ig3U1pM7j995g8D6g+rdKv7XwzHJOu5HBL9r1DnGd4ypN0IAJlZ+uYbWSqNeQ0f40/Fgmpjv20m47WN/R9OL/acsAGI=
      edge:
        source: Nemo157/dpl
        branch: crates.io
      on:
        all_branches: true

branches:
  only: [staging, trying, master]
