language: rust
sudo: false
cache: cargo

rust:
- 1.20.0
- stable
- beta
- nightly

script:
- cargo test --all
- cargo test --all --release

matrix:
  allow_failures:
  - rust: nightly
  include:
  - os: osx
    rust: stable
  - env: RUSTFMT
    rust: nightly-2018-06-18
    install:
    - rustup component add rustfmt-preview
    script:
    - cargo fmt -- --check
  - env: CLIPPY_VERSION=0.0.179
    rust: nightly-2018-01-12
    install:
    - which cargo-clippy || cargo install clippy --version $CLIPPY_VERSION
    script:
    - cargo clippy -- -D warnings
