language: rust
sudo: false
cache: cargo

script:
- cargo test --all
- cargo test --all --release

matrix:
  allow_failures:
  - rust: nightly
  include:
  - os: osx
  - rust: 1.20.0
  - rust: stable
  - rust: beta
  - rust: nightly
  - env: RUSTFMT
    rust: nightly-2018-06-18
    install:
    - rustup component add rustfmt-preview
    script:
    - cargo fmt -- --write-mode=diff
  - env: CLIPPY_VERSION=0.0.179
    rust: nightly-2018-01-12
    install:
    - which cargo-clippy || cargo install clippy --version $CLIPPY_VERSION
    script:
    - cargo clippy -- -D warnings
