version: 2.1

orbs:
  rust: nemo157/rust@dev:alpha

workflows:
  version: 2.1
  test:
    jobs:
    - rust/check
    - rust/fmt
    - rust/clippy:
        requires: [rust/check]
    - rust/test:
        requires: [rust/check]
    - rust/test:
        name: rust/test minimal-versions
        minimal-versions: true
        requires: [rust/check]

  daily:
    jobs:
    - rust/check
    - rust/fmt
    - rust/clippy:
        requires: [rust/check]
    - rust/test:
        requires: [rust/check]
    - rust/test:
        name: rust/test minimal-versions
        minimal-versions: true
        requires: [rust/check]
    triggers:
    - schedule:
        cron: "0 0 * * *"
        filters: {branches: {only: [rust-orb]}}
