version: 2.1

executors:
  rust:
    docker:
    - image: circleci/rust:latest

jobs:
  build:
    executor: rust
    steps:
    - checkout
    - run:
        command: cargo build
    - persist_to_workspace:
        root: target
        paths:
        - debug

  test:
    executor: rust
    steps:
    - checkout
    - attach_workspace:
        at: target
    - run:
        command: cargo test

  minimal:
    executor: rust
    steps:
    - checkout
    - run:
        command: rustup default nightly
    - run:
        command: cargo update -Z minimal-versions
    - run:
        command: cargo test

  fmt:
    executor: rust
    steps:
    - checkout
    - run:
        command: rustup component add rustfmt
    - run:
        command: cargo fmt --all -- --check

  clippy:
    executor: rust
    steps:
    - checkout
    - attach_workspace:
        at: target
    - run:
        command: rustup component add clippy
    - run:
        command: cargo clippy --all --all-targets -- -D warnings

workflows:
  version: 2.1
  test:
    jobs:
    - build
    - test:
        requires:
        - build
    - minimal
    - fmt
    - clippy:
        requires:
        - build
